[package]
name = "reedbed"
description = "frontend for approximating thermal energy using the reedbed libarry"
version = "0.0.0"
authors = ["superwhiskers <whiskerdev@protonmail.com>"]
repository = "https://github.com/superwhiskers/reedbed"
readme = "../readme.md"
keywords = ["numerical-approximation", "scientific-computing"]
categories = ["Science", "Simulation", "Mathematics"]
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
rug = "1"
mimalloc = "0.1"

[dependencies.reedbed-lib]
path = "../../lib"
version = "*"
